### ISSUE TITLE
'gdm.service fails' issue

### ISSUE THREAD

**Issue by dcasota** [Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware#1]

**Comment by Master-Koy** [comment]
> @Master-Koy Please cleanup your questions in photon github.
> 
> You could try to generate diagnostics data.
> 
> 1. Reboot the system and boot until the 'gdm.services fails' issue occurs.
> 2. If the issue still occurs, boot from console root (init=/bin/bash) and run `dmesg` and `journalctl -b 1`. Add that output e.g. here.

I'm unable to send whole `dmesg` output because it's too long. How do I send that whole thing. Unable to go up.

Below is the `journalctl -b 1` output:
![jo5](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/156993314/600f32dd-d30e-4331-8f75-6db66a7d9774)

**Comment by dcasota** [comment]
You still see the 'gdm.service fails' issue on the same vm as the journalctl log, right?
The logfile extract is from January 1st. It seems okay. You need that logfile extract with information about the gdm.service issue, e.g. by `journalctl --boot --priority=err`.

**Comment by Master-Koy** [comment]
> You still see the 'gdm.service fails' issue on the same vm as the journalctl log, right? The logfile extract is from January 1st. It seems okay. You need that logfile extract with information about the gdm.service issue, e.g. by `journalctl --boot --priority=err`.

It says like this:
![41](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/156993314/0df23840-40b8-4c8e-961e-32898a5aaf7d)

**Comment by Master-Koy** [comment]
> You still see the 'gdm.service fails' issue on the same vm as the journalctl log, right? The logfile extract is from January 1st. It seems okay. You need that logfile extract with information about the gdm.service issue, ~e.g. by `journalctl --boot --priority=err`.~

It says like this:
![2130](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/156993314/00e18402-5edc-48bd-94dd-d7d1a3c3e524)

**Comment by dcasota** [comment]
Unfortunately I cannot reproduce the 'gdm.service fails' issue. In recovery mode, see apt search commands to check the versions.
![image](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/14890243/7d8cca0a-81f5-4af0-a90d-0fcaa7795850)

**Comment by Master-Koy** [comment]
> Unfortunately I cannot reproduce the 'gdm.service fails' issue. In recovery mode, see apt search commands to check the versions. ![image](https://private-user-images.githubusercontent.com/14890243/299723251-7d8cca0a-81f5-4af0-a90d-0fcaa7795850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTgwOTEsIm5iZiI6MTcwNjE5Nzc5MSwicGF0aCI6Ii8xNDg5MDI0My8yOTk3MjMyNTEtN2Q4Y2NhMGEtODFmNS00YWYwLWE5MGQtMGZjYWE3Nzk1ODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE1NDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMDlhYjRkNjIzMmEwNWVmYTQzNmYwODQ0ZDQ0NWNiM2NmYzM3YTJhMjk4MWJjYTczNTU1MjQwMDUxMmYwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O_rCwD8p6Hh7qv3BgxahZrhI2djBbJQIqP-AABRxwNE) Somehow it should be possible to reinstall lightdm, the default desktop manager, at least that is was I would do. `sudo dpkg-reconfigure lightdm`?

See:
![123](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/156993314/74cda1d4-66fb-4b12-b50c-8ff97e928825)

**Comment by dcasota** [comment]
Can you restart in recovery mode, and retry there?

**Comment by Master-Koy** [comment]
How to get in that ?

**Comment by dcasota** [comment]
Workstation > restart guest > advanced options for kali/(gnu)linux > 2nd choice (recovery mode)

**Comment by Master-Koy** [comment]
![50](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/156993314/3d842c02-fe8c-420f-8279-edfb61395b40)


![942](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/156993314/06a13add-15f1-47ff-8c4c-76fe8b2b4130)

Which one should I go for ?

**Comment by dcasota** [comment]
I don't know. Your system has multiple entries and not two only. On that entry were you started `sudo systemctl disable gdm.service`, root is locked, so systemctl does not work.

**Comment by Master-Koy** [comment]
> I don't know. Your system has multiple entries and not two only. On that entry were you started `sudo systemctl disable gdm.service`, root is locked, so systemctl does not work.

![51](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/156993314/16d79310-9260-4f76-a8d4-dc963c27c01f)
 This is in recovery mode.
What should I do now ?

**Comment by dcasota** [comment]
Accordingly to the output, the goal of reconfiguring lightdm did not work. Both console commands failed.
what do you get for `uname -a` output on that system? /usr/share/perl5 .. I would try to get more vm information.

On the test system without the 'gdm.service fails' issue I get `Linux kali 6.5.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09) x86_64 GNU/Linux`.

**Comment by Master-Koy** [comment]
This is in Recovery Mode, same here see:

![una](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/156993314/fbd0d94d-dd87-46be-89e1-6002239961fb)

**Comment by dcasota** [comment]
In summary,

## Event
`sudo apt-get update` and `sudo apt-get upgrade` started on Kali-Linux. Then,
on VMware By Broadcom Workstation you've pressed poweroff, right? Or was it the host system with VMware By Broadcom Workstation installed on it that lost electric power? Actually I think it does not matter because since then, Kali-Linux does not come up.

## No LightDM
Lightdm is NOT installed on it. This is not correlated to poweroff during installation. So, there must have been a packages configuration attempt before apt-get update/upgrade to use Kali Linux without lightdm, but to use gdm.

## Snapshot
You didn't use the snapshot possibility of VMware By Broadcom Workstation before any reconfiguration/install.

## Findings
I'm afraid, actually my knowledge is little to be trustworthy enough for packages dependency analytics of the repo, delete/purge and cleanup.

If you have valuable data on that system, and you don't know how to save, then you need experts. You can reach the filesystem at least, hence you might be able to save the data.

I would install a new Kali-Linux vm.

Hope this helps.
Daniel

**Comment by Master-Koy** [comment]
Exactly this is the exact issue. I'm trying to explain everyone.

That sounds not good. Maybe it's going to take a very long to get the experts you are saying.

Hopeless 😢

**Comment by dcasota** [comment]
In which folder do you have valuable data stored?

**Comment by Master-Koy** [comment]
In this directory:

/home/(my-username)/

**Comment by dcasota** [comment]
okay, good, so what you could do is copying the content folder from the mounted virtual disk to the disk in another vm.
Here a description attempt.

Note: The steps assume that you have a functional virtual machine to which you want to attach the virtual hard disk. If you do not have a functional virtual machine

1. in VMware By Broadcom Workstation, shutdown this vm, let's call it vm1.

2. Check the path of the virtual disk. You will need that path on the other vm.
![image](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/14890243/f485dd38-c30e-4a80-8335-bd6b0efe09f6)

3. In VMware By Broadcom Workstation, you need another vm, let's call it vm2. This can be another Kali-Linux vm. If you haven't one, create one.

4. The configured vm2 should be powered off. In the virtual machine settings, add a hard disk. In that 'add hardware wizard' select 'use an existing virtual disk', and browse to the path of the virtual disk of vm1, the source kali linux vm. Choose the virtual disk file e.g. kali-linux-2024-W04-vmware-amd64.vmdk. Keep existing format. Save the vm settings.
![image](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/14890243/6d165740-e8e8-40a5-8ced-da6fa7240228)

5. Leave vm1 powered off. Boot from vm2. Assuming you can use the lightdm kali-linux interface in vm2, login and open a console window. `sudo fdisk -l` should show the drive letter of the attached virtual disk.
![image](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/14890243/6e6518d4-c7d4-45bd-b2fe-d72d0c7b7f0f)


6. On the partition of the added disk you should find your /home/(my-username)/ folder, and save the folder e.g. locally or on your network.
`sudo mkdir -p $HOME/savedata`
`# /dev/sdb1 is from vm2 and listed in fdisk -l`
`sudo mount /dev/sdb1 $HOME/savedata`

![image](https://github.com/Master-Koy/-Boot-Error-Stuck-at-Boot-in-Kali-Linux-in-Vmware/assets/14890243/23931ade-59ba-4851-bb99-420060dfb395)


7. After having saved the data, shutdown vm2. Detach (delete without purging the disk file) the added disk from vm2, and save the vm2 settings.

If you have saved and backuped the /home/(my-username)/ data, and if you do not need anything from vm1 anymore, you can delete that vm1 completely. 

_packages dependency analytics of the repo, delete/purge and cleanup_
This knowledge highly depends on the distro. As a Photon OS enthusiast, I still know little about Photon OS packages dependencies with respect to flavors, rpm-ostree, bios/uefi, cpu architecture, etc. Of course, it get's easier after a few years, but I guess Kali-Linux packages know-how expands with a similar learning curve characteristic.


不幸的是，我只学了英语，没有学中文。我使用谷歌翻译。

**Comment by Master-Koy** [comment]
@dcasota it worked !
I was able to recover my files and I have got a new fresh install also. 

I really appreciate your effort. The commitment you gave in helping my issue. Let me know if I can do anything for you, I know I'm not any expert but still I'll try my best. You are such a great person. May **GOD** Bless You.  Once again thank you so much brother !!!!
